" @author nate zhou
" @since 2023,2024,2025

source ${HOME}/.config/vim/autocmd.vim
source ${HOME}/.config/vim/bindings.vim

set viminfofile=~/.config/vim/viminfo


"colorscheme unixchad
syntax on
if &diff
    syntax off
    colorscheme industry
endif
set encoding=utf-8
set title           " terminal title
set background=dark
set mouse=          " disable mouse clicks
set clipboard=unnamedplus

" set nohlsearch
set ignorecase      " case insensitive searching
set smartcase       " search case insensitive; if upper exists sensitive;

set number
set relativenumber
set cc=80
set cursorline
set cursorcolumn
"match ExtraWhitespace /\s\+$/ " space at the end of lines
"highlight ExtraWhitespace ctermbg=gray guibg=gray " highlight all trailing spaces
set laststatus=2
set statusline+=%f\ %h%m%r%=\ %-16.(%)\ %c[%l/%L\ %P]

" don't yank to clipboard with c
nnoremap c "_c

set expandtab		" expand tab input with spaces
set tabstop=4		" spaces per tab
set shiftwidth=4	" spaces per indentation level
set smartindent		" aware indentations for newline insert
set splitbelow splitright " new split position
