# @author nate zhou
# @since 2023,2024
# codeberg.org/unixchad/dotfiles
# github.com/gnuunixchad/dotfiles
# my vim-like and sway-like tmux keybindings

# change Prefix Key (like mod key)
set-option -g prefix C-w
unbind-key C-w
bind-key C-w send-prefix
set -g base-index 1

bind-key n display-panes
bind-key : command-prompt
# reload confing
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "sources tmux.conf"

### pane (like window split) ###
bind-key v split-window -h
unbind-key x
bind-key x split-window -v
bind-key o rotate-window
bind-key q kill-pane
# change focus around panes
bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R
# resize panes
bind-key i resize-pane -U 5
bind-key u resize-pane -D 5
bind-key y resize-pane -L 5
bind-key o resize-pane -R 5

### window (like workspace) ###
# [default] prefix+number to move to a specific window
bind-key enter new-window
bind-key -n C-. next-window
bind-key -n C-, previous-window

### color ###
set -g pane-border-style 'fg=yellow'
set -g pane-active-border-style 'fg=red'

set -g status-right-style 'fg=white bg=#005577'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

setw -g window-status-current-style 'fg=#eeeeee bg=#9962b7'
setw -g window-status-current-format ' #I #W #F '
setw -g window-status-style 'fg=white bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=white]#F '
setw -g window-status-bell-style 'fg=yellow bg=red bold'

set -g status-bg black
set -g status-fg white
