#!/usr/bin/sh
# @author nate zhou
# @since 2025
# river/autostart

# always
riverctl spawn "${HOME}/.local/bin/dam-run"

# restart
killall -q swaybg fcitx5 mpc

riverctl spawn "swaybg -i ${HOME}/.local/share/wallpaper -m fill"
#riverctl spawn "swaybg -c 000000"

# restart decided by scripts
riverctl spawn "${HOME}/.local/bin/foots"

riverctl spawn "${HOME}/.local/sbin/clsd"

riverctl spawn "${HOME}/.local/bin/mbs-cron"

# start if not running
pgrep 'swayidle' || riverctl spawn "swayidle"

pgrep 'kanshi' || riverctl spawn "kanshi"

pgrep "gammastep" || riverctl spawn "gammastep -O 5000"

pgrep -f 'wl-paste --watch cliphist store' || riverctl spawn "wl-paste --watch cliphist store"

pgrep 'dunst' || riverctl spawn "dunst"

pgrep 'wob' || riverctl spawn "${HOME}/.local/bin/wobd"

riverctl spawn "fcitx5 -d" # conflicts with wtype
