#!/usr/bin/sh
# @author nate zhou
# @since 2025,2026
# river/init
# river-0.4.0

# my build of kwm
# https://codeberg.org/unixchad/kwm
# https://github.com/gnuunixchad/kwm
${HOME}/.local/bin/damblocks | /usr/local/bin/kwm &

killall -q mpc
${HOME}/.local/bin/damblocks-mpdd
