#wayland support for vscode and code-oss
##commented for having `export ELECTRON_OZONE_PLATFORM_HINT=wayland` in ~/.profile
#--ozone-platform-hint=wayland

#--enable-features=WaylandWindowDecorations
#--ozone-platform-hint=auto
